/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

@Data
@EqualsAndHashCode(callSuper=false) 
@Entity
@Table(name = "Address")
public class Address extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
    private Long id;

    @Column(name = "suite", length = 45)
    @Basic
    private String suite;

    @Column(name = "street_name", length = 45)
    private String streetName;

    @Column(name = "street_no")
    private Integer streetNo;

    @Column(name = "building_name", length = 45)
    @Basic
    private String buildingName;

    @Column(name = "community", length = 45)
    @Basic
    private String communityName;

    @Column(name = "district", length = 45)
    @Basic
    private String districtName;

    @Column(name = "city")
    @Basic
    private String cityName;

    @Column(name = "state")
    @Basic
    private String stateName;

    @Column(name = "country")
    @Basic
    private String countryName;

    @Column(name = "postal_code", length = 20)
    @Basic
    private String postalCode;

    @OneToOne(fetch = FetchType.LAZY, targetEntity = ContactAddress.class)
    private ContactAddress contactAddress;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = AddressType.class)
    @JoinColumn(name = "TYPE_ID", referencedColumnName = "ID")
    private AddressType type;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = City.class)
    @JoinColumn(name = "CITY_ID", referencedColumnName = "ID")
    private City city;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Community.class)
    @JoinColumn(name = "COMMUNITY_ID", referencedColumnName = "ID")
    private Community community;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Country.class)
    @JoinColumn(name = "COUNTRY_ID", referencedColumnName = "ID")
    private Country country;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Province.class)
    @JoinColumn(name = "PROVINCE_ID", referencedColumnName = "ID")
    private Province province;

}