/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.NaturalId;

import javax.persistence.*;

@Data
@EqualsAndHashCode(callSuper=false)
//@ToString
@Entity
@Table(name = "Authority")
@Immutable
public class Authority {
	
	public static final int ID_ROLE_USER = 1;
	public static final int ID_ROLE_ADMIN = 2;
	public static final String DEFAULT_ROLE_USER = "ROLE_USER";

    @Column(name = "id", nullable = false)
    @Id 
    @NaturalId
    private Integer id;

    @Column(name = "name", nullable = false, length = 50)
    @Basic(optional = false)
    private String name;

    @Column(name = "description")
    @Basic
    private String description;

    @Column(name = "code")
    @Basic
    private String code;

}