/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import java.math.BigDecimal;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) 
@MappedSuperclass
public class BasicAdjustment extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "reason")
    @Basic
    private String reason;

    @Column(name = "amount", scale = 5, precision = 19)
    @Basic
    private BigDecimal amount;

    @Column(name = "rank")
    @Basic
    private Integer rank;

}