/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import java.math.BigDecimal;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) 
@MappedSuperclass
public class BasicPayment extends AuditableBaseEntity  {

    @Column(name = "id", nullable = false)
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")	
    private Long id;

    @Column(name = "amount", scale = 5, precision = 19)
    @Basic
    private BigDecimal amount;

    @Column(name = "archived")
    @Basic
    private Boolean archived;

    @Column(name = "reference_no")
    @Basic
    private String referenceNo;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Currency.class)
    @JoinColumn(name = "CURRENCY_ID", referencedColumnName = "ID")
    private Currency currency;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Gateway.class)
    @JoinColumn(name = "GATEWAY_ID", referencedColumnName = "ID")
    private Gateway gateway;

}