/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) 
@Entity
@Table(name = "Community")
public class Community {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "name")
    @Basic
    private String name;

    @Column(name = "code")
    @Basic
    private String code;

    @Column(name = "zone")
    @Basic
    private String zone;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = City.class)
    @JoinColumn(name = "CITY_ID", referencedColumnName = "ID")
    private City cityId;

}