/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "ContactInfo")
public class ContactInfo extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "contact")
    @Basic
    private String content;

    @Column(name = "extension")
    @Basic
    private String extension;

    @Column(name = "rank")
    @Basic
    private Integer rank;

    @ManyToOne(optional = false, cascade = {CascadeType.PERSIST}, fetch = FetchType.LAZY, targetEntity = Contact.class)
    @JoinColumn(name = "CONTACT_ID", referencedColumnName = "ID")
    private Contact contact;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = ContactType.class)
    @JoinColumn(name = "TYPE_ID", referencedColumnName = "ID")
    private ContactType type;

}