/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) 
@Entity
@Table(name = "Contact_Address"
//	, uniqueConstraints = {@UniqueConstraint(columnNames = {"address_id"})}
)
public class ContactAddress extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @OneToOne(fetch = FetchType.LAZY, targetEntity = Address.class, mappedBy = "contactAddress")
    @JoinColumn(name = "ADDRESS_ID", referencedColumnName = "ID")
    private Address addressId;

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = Contact.class)
    @JoinColumn(name = "CONTACT_ID", referencedColumnName = "ID")
    private Contact contactId;

}