/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.List;

@Data
@EqualsAndHashCode(callSuper=false) 
@Entity
@Table(name = "Contact")
public class Contact extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
    private Long id;

    @Column(name = "firstname")
    @Basic
    private String firstname;

    @Column(name = "lastname")
    @Basic
    private String lastname;

    @Column(name = "gender")
    @Basic
    private Integer gender;

    @Column(name = "avatar")
    @Basic
    private String avatar;

    @OneToMany(cascade = CascadeType.ALL, targetEntity = UserContact.class, mappedBy = "contact")
    private List<UserContact> contacts;



}