/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "Corporate_Address"
//	, uniqueConstraints = {@UniqueConstraint(columnNames = {"address_id"})}
)
public class CorporateAddress extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
    private Long id;

    @OneToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Address.class)
    @JoinColumn(name = "ADDRESS_ID", referencedColumnName = "ID")
    private Address address;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Corporate.class)
    @JoinColumn(name = "CORPORATE_ID", referencedColumnName = "ID")
    private Corporate corporate;

}