/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.List;

@Data
@EqualsAndHashCode(callSuper=false)
@Entity
@Table(name = "Corporate")
public class Corporate extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
    private Long id;

    @Column(name = "name", length = 45)
    @Basic
    private String name;

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = Address.class)
    @JoinColumn(name = "ADDRESS_ID", referencedColumnName = "ID")
    private Address address;

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = TouchUser.class)
    @JoinColumn(name = "OWNER_ID", referencedColumnName = "ID")
    private TouchUser owner;

    @OneToMany(targetEntity = CorporateAddress.class, mappedBy = "corporate")
    private List<CorporateAddress> corporateAddressCollection;

}