/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.time.ZonedDateTime;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "Credit_Card")
public class CreditCard extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "card_no", length = 16)
    @Basic
    private String cardNo;

    @Column(name = "type")
    @Basic
    private Integer type;

    @Column(name = "name", length = 45)
    @Basic
    private String name;

    @Column(name = "pin", length = 3)
    @Basic
    private String pin;

    @Column(name = "expiry", length = 4)
    @Basic
    private String expiry;

    @Column(name = "token")
    @Basic
    private String token;

    @Column(name = "token_expiry")
    @Basic
//    @Temporal(TemporalType.TIMESTAMP)
    private ZonedDateTime tokenExpiry;

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = TouchUser.class)
    @JoinColumn(name = "OWNER_ID", referencedColumnName = "ID")
    private TouchUser owner;

}