/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.List;

@Data
@EqualsAndHashCode(callSuper=false)
@Entity
@Table(name = "Device")
public class Device extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "name", length = 45)
    @Basic
    private String name;

    @Column(name = "serial", length = 45)
    @Basic
    private String serial;

    @Column(name = "type")
    @Basic
    private Integer type;

    @OneToMany(targetEntity = UserDevice.class, mappedBy = "device")
    private List<UserDevice> userDeviceCollection;

}