/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import com.vividsolutions.jts.geom.Point;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) 
@Entity
@Table(name = "Device_Track")
public class DeviceTrack extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "lat")
    @Type(type = "org.geolatte.geom.GeometryType")        
    private Point lat;

    @Column(name = "log")
    @Type(type = "org.geolatte.geom.GeometryType")    
    private Point log;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = UserDevice.class)
    @JoinColumn(name = "USER_DEVICE_ID", referencedColumnName = "ID")
    private UserDevice userDevice;

}