/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "Document_Type")
public class DocumentType {

    @Column(name = "id", nullable = false)
    @Id 
    private Integer id;

    @Column(name = "name", nullable = false)
    @Basic(optional = false)
    private String name;
    
    @Column(name = "code", nullable = false)
    private String code;

}