/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import com.vividsolutions.jts.geom.Point;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) 
@Entity
@Table(name = "Event")
public class Event extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")	
    private Long id;

    @Column(name = "user_hash_id")
    @Basic
    private String userHashId;

    @Column(name = "lat")
    @Type(type = "org.geolatte.geom.GeometryType")    
    private Point lat;

    @Column(name = "log")
    @Type(type = "org.geolatte.geom.GeometryType")
    private Point log;

    @Column(name = "event_type")
    @Basic
    private String eventType;

    @Column(name = "event_value")
    @Basic
    private String eventValue;

    @Column(name = "device_id")
    @Basic
    private Long deviceId;

}