/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import com.fasterxml.jackson.annotation.JsonView;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

@Data
@EqualsAndHashCode(callSuper=false)
@Entity
@Table(name = "File")
public class File extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "protocol", length = 45)
    @Basic
    private String protocol;

    @Column(name = "file_path", length = 45)
    @Basic
    @JsonView(Frontend.class)
    private String filePath;

}