/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.time.ZonedDateTime;
import java.util.List;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "QR_Code"
//	, uniqueConstraints = {@UniqueConstraint(columnNames = {"code"})}
)
public class QRCode  extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	private Long id;

    @Column(name = "code", nullable = false)
    @Basic(optional = false)
    private String code;

    @Column(name = "value", nullable = false)
    @Basic(optional = false)
    private String value;

    @Column(name = "url")
    @Basic
    private String url;

    @Column(name = "expiry")
    private ZonedDateTime expiry;

    @Column(name = "type")
    @Basic
    private String type;

    @OneToMany(targetEntity = QRScanLog.class, mappedBy = "qrCode")
    private List<QRScanLog> qRScanLogCollection;


}