/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "QR_Scan_Log")
public class QRScanLog  extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "user_hash_id")
    @Basic
    private String userHashId;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Event.class)
    @JoinColumn(name = "EVENT_ID", referencedColumnName = "ID")
    private Event event;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = QRCode.class)
    @JoinColumn(name = "QR_CODE_ID", referencedColumnName = "ID")
    private QRCode qrCode;

}