/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.time.ZonedDateTime;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "User_Corporate")
public class UserCorporate extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "start_dt")
    @Basic
//    @Temporal(TemporalType.TIMESTAMP)
    private ZonedDateTime startDt;

    @Column(name = "end_dt")
    @Basic
//    @Temporal(TemporalType.TIMESTAMP)
    private ZonedDateTime endDt;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Corporate.class)
    @JoinColumn(name = "CORPORATE_ID", referencedColumnName = "ID")
    private Corporate corporate;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = TouchUser.class)
    @JoinColumn(name = "USER_ID", referencedColumnName = "ID")
    private TouchUser touchUser;

}