/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) 
@Entity
@Table(name = "User_Preference")
public class UserPreference extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @Column(name = "device_id")
    @Basic
    private Long deviceId;

    @Column(name = "notification_ind")
    @Basic
    private Boolean notificationInd;

    @Column(name = "track_ind")
    @Basic
    private Boolean trackInd;

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = TouchUser.class)
    @JoinColumn(name = "USER_ID", referencedColumnName = "ID")
    private TouchUser touchUser;

}