/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper=false, exclude="touchUser")
@ToString(callSuper=false, exclude="touchUser")
@Entity
@Table(name = "User_Connection_Wechat")
public class UserConnectionWechat extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")	
    private Long id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER, targetEntity = TouchUser.class)
    @JoinColumn(name = "USER_ID", referencedColumnName = "ID")
    private TouchUser touchUser;

    @Column(name = "app_id")
    @Basic
    private String appId;

    @Column(name = "open_id")
    @Basic
    private String openId;

    @Column(name = "union_id")
    @Basic
    private String unionId;

    @Column(name = "subscribe")
    @Basic
    private Boolean subscribe;

    @Column(name = "session_key")
    @Basic
    private String sessionKey;

    @Column(name = "expires")
    @Basic
    private Long expires;

    @Column(name = "nickname")
    @Basic
    private String nickname;

    @Column(name = "sex")
    @Basic
    private Integer sex;

    @Column(name = "city")
    @Basic
    private String city;

    @Column(name = "province")
    @Basic
    private String province;

    @Column(name = "country")
    @Basic
    private String country;

    @Column(name = "language")
    @Basic
    private String language;

    @Column(name = "avatar_Url")
    @Basic
    private String avatarUrl;

    @Column(name = "subscribe_time")
    @Basic
    private Long subscribeTime;

    @Column(name = "remark")
    @Basic
    private String remark;

}