/**
 * This file was generated by the Jeddict
 */
package technology.touchmars.template.model;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper=false) @Entity
@Table(name = "User_Device")
public class UserDevice extends AuditableBaseEntity {

    @Column(name = "id", nullable = false)
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="native")
	@GenericGenerator(name = "native", strategy = "native")
	
    private Long id;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = Device.class)
    @JoinColumn(name = "DEVICE_ID", referencedColumnName = "ID")
    private Device device;

    @ManyToOne(optional = false, fetch = FetchType.LAZY, targetEntity = TouchUser.class)
    @JoinColumn(name = "USER_ID", referencedColumnName = "ID")
    private TouchUser touchUser;

    @OneToMany(targetEntity = DeviceTrack.class)
    private List<DeviceTrack> deviceTrackCollection;

}